<a href="https://colab.research.google.com/github/FernandoCallasaca/data_science_projects/blob/main/8_concat_append.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Preparamos nuestro lugar de trabajo

## Drive

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
%cd '/content/drive/My Drive/Data Science/Platzi/10. Curso de Manipulación y Análisis de datos con Pandas y Python/db/'
!ls

/content/drive/My Drive/Data Science/Platzi/10. Curso de Manipulación y Análisis de datos con Pandas y Python/db
london_merged.csv  Meteorite_Landings.csv  notas.csv  population-worldbank


In [4]:
def path_file(name_file):
  return '/content/drive/My Drive/Data Science/Platzi/10. Curso de Manipulación y Análisis de datos con Pandas y Python/db/{0}'.format(name_file)

## Librerías

In [6]:
import pandas as pd
import numpy as np
import seaborn as sn
import matplotlib.pyplot as plt
%matplotlib inline
pd.__version__

'1.1.5'

In [8]:
# para pandas = 2 decimales y seperación con , los miles
pd.options.display.float_format = '{:,.2f}'.format

In [9]:
# para numpy la presición en 2 decimales
np.set_printoptions(precision=2)

In [18]:
# creamos una matriz de 2 por 5 con valores entre 0 y 100 aleatorios
# rand = [0, 1]
# randn = [-1, 1]
x1 = np.random.rand(2,5)*10
x1

array([[2.76, 5.74, 0.04, 9.87, 6.44],
       [2.81, 8.8 , 8.11, 0.83, 7.45]])

In [19]:
x2 = np.random.rand(2,5)*-1
x2

array([[-0.9 , -0.56, -0.13, -0.13, -1.  ],
       [-0.27, -0.57, -0.93, -0.05, -0.96]])

In [20]:
# concatenamos matrices
np.concatenate([x1,x2])

array([[ 2.76,  5.74,  0.04,  9.87,  6.44],
       [ 2.81,  8.8 ,  8.11,  0.83,  7.45],
       [-0.9 , -0.56, -0.13, -0.13, -1.  ],
       [-0.27, -0.57, -0.93, -0.05, -0.96]])

In [21]:
np.concatenate([x1,x2]).shape

(4, 5)

In [22]:
np.concatenate([x1,x2], axis = 1)

array([[ 2.76,  5.74,  0.04,  9.87,  6.44, -0.9 , -0.56, -0.13, -0.13,
        -1.  ],
       [ 2.81,  8.8 ,  8.11,  0.83,  7.45, -0.27, -0.57, -0.93, -0.05,
        -0.96]])

In [23]:
np.concatenate([x1,x2], axis = 1).shape

(2, 10)