<a href="https://colab.research.google.com/github/FernandoCallasaca/data_science_projects/blob/main/8_concat_append.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Preparamos nuestro lugar de trabajo

## Drive

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
%cd '/content/drive/My Drive/Data Science/Platzi/10. Curso de Manipulación y Análisis de datos con Pandas y Python/db/'
!ls

/content/drive/My Drive/Data Science/Platzi/10. Curso de Manipulación y Análisis de datos con Pandas y Python/db
london_merged.csv  Meteorite_Landings.csv  notas.csv  population-worldbank


In [4]:
def path_file(name_file):
  return '/content/drive/My Drive/Data Science/Platzi/10. Curso de Manipulación y Análisis de datos con Pandas y Python/db/{0}'.format(name_file)

## Librerías

In [5]:
import pandas as pd
import numpy as np
import seaborn as sn
import matplotlib.pyplot as plt
%matplotlib inline
pd.__version__

'1.1.5'

In [6]:
# para pandas = 2 decimales y seperación con , los miles
pd.options.display.float_format = '{:,.2f}'.format

In [7]:
# para numpy la presición en 2 decimales
np.set_printoptions(precision=2)

In [9]:
# creamos una matriz de 2 por 5 con valores entre 0 y 100 aleatorios
# rand = [0, 1]
# randn = [-1, 1]
x1 = np.random.rand(2,5)*10
x1

array([[7.39, 3.84, 7.76, 9.72, 5.11],
       [3.69, 6.28, 3.67, 7.67, 0.88]])

In [10]:
x2 = np.random.rand(2,5)*-1
x2

array([[-0.02, -0.16, -0.97, -0.79, -0.83],
       [-0.57, -0.15, -0.47, -0.58, -0.33]])

In [11]:
# concatenamos matrices
np.concatenate([x1,x2])

array([[ 7.39,  3.84,  7.76,  9.72,  5.11],
       [ 3.69,  6.28,  3.67,  7.67,  0.88],
       [-0.02, -0.16, -0.97, -0.79, -0.83],
       [-0.57, -0.15, -0.47, -0.58, -0.33]])

In [12]:
np.concatenate([x1,x2]).shape

(4, 5)

In [13]:
np.concatenate([x1,x2], axis = 1)

array([[ 7.39,  3.84,  7.76,  9.72,  5.11, -0.02, -0.16, -0.97, -0.79,
        -0.83],
       [ 3.69,  6.28,  3.67,  7.67,  0.88, -0.57, -0.15, -0.47, -0.58,
        -0.33]])

In [14]:
np.concatenate([x1,x2], axis = 1).shape

(2, 10)

In [15]:
s1 = pd.Series(x1[0], index = ['a','b','c','d','e'])
s1

a   7.39
b   3.84
c   7.76
d   9.72
e   5.11
dtype: float64

In [16]:
s2 = pd.Series(x2[0], index = ['c','d','e','f','g'])
s2

c   -0.02
d   -0.16
e   -0.97
f   -0.79
g   -0.83
dtype: float64

In [19]:
pd.concat([s1, s2], ignore_index = True, axis = 1)

0     1
a 7.39   nan
b 3.84   nan
c 7.76 -0.02
d 9.72 -0.16
e 5.11 -0.97
f  nan -0.79
g  nan -0.83

In [20]:
s1.reset_index(drop = True, inplace = True)
s1

0   7.39
1   3.84
2   7.76
3   9.72
4   5.11
dtype: float64

In [21]:
s2.reset_index(drop = True, inplace = True)
s2

0   -0.02
1   -0.16
2   -0.97
3   -0.79
4   -0.83
dtype: float64

In [22]:
pd.concat([s1,s2], axis = 1, ignore_index = True)

0     1
0 7.39 -0.02
1 3.84 -0.16
2 7.76 -0.97
3 9.72 -0.79
4 5.11 -0.83

In [23]:
df1 = pd.DataFrame(np.random.rand(3,2)*10, columns = ['a', 'b'])
df1

a    b
0 0.09 2.43
1 0.62 1.86
2 3.85 8.02

In [24]:
df2 = pd.DataFrame(np.random.rand(3,2)*-1, columns = ['a', 'b'], index = [2,3,4])
df2

a     b
2 -0.81 -0.78
3 -0.93 -0.04
4 -0.75 -0.01

In [27]:
pd.concat([df1,df2], axis = 0, ignore_index=False)

a     b
0  0.09  2.43
1  0.62  1.86
2  3.85  8.02
2 -0.81 -0.78
3 -0.93 -0.04
4 -0.75 -0.01

In [28]:
pd.concat([df1,df2], axis = 1, ignore_index=False)

a    b     a     b
0 0.09 2.43   nan   nan
1 0.62 1.86   nan   nan
2 3.85 8.02 -0.81 -0.78
3  nan  nan -0.93 -0.04
4  nan  nan -0.75 -0.01

In [30]:
pd.concat([df1,df2], axis = 1, ignore_index=False, join='inner')

a    b     a     b
2 3.85 8.02 -0.81 -0.78

In [32]:
pd.concat([df1.reset_index(drop=True)
           ,df2.reset_index(drop=True)
           ], axis = 1, ignore_index=False)

a    b     a     b
0 0.09 2.43 -0.81 -0.78
1 0.62 1.86 -0.93 -0.04
2 3.85 8.02 -0.75 -0.01

In [35]:
df1.T.append(df2.T).T

a    b     a     b
0 0.09 2.43   nan   nan
1 0.62 1.86   nan   nan
2 3.85 8.02 -0.81 -0.78
3  nan  nan -0.93 -0.04
4  nan  nan -0.75 -0.01

In [33]:
df1.append(df2)

a     b
0  0.09  2.43
1  0.62  1.86
2  3.85  8.02
2 -0.81 -0.78
3 -0.93 -0.04
4 -0.75 -0.01

In [34]:
df1.T

0    1    2
a 0.09 0.62 3.85
b 2.43 1.86 8.02