<a href="https://colab.research.google.com/github/FernandoCallasaca/data_science_projects/blob/main/8_concat_append.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Preparamos nuestro lugar de trabajo

## Drive

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
%cd '/content/drive/My Drive/Data Science/Platzi/10. Curso de Manipulación y Análisis de datos con Pandas y Python/db/'
!ls

/content/drive/My Drive/Data Science/Platzi/10. Curso de Manipulación y Análisis de datos con Pandas y Python/db
london_merged.csv  Meteorite_Landings.csv  notas.csv  population-worldbank


In [4]:
def path_file(name_file):
  return '/content/drive/My Drive/Data Science/Platzi/10. Curso de Manipulación y Análisis de datos con Pandas y Python/db/{0}'.format(name_file)

## Librerías

In [6]:
import pandas as pd
import numpy as np
import seaborn as sn
import matplotlib.pyplot as plt
%matplotlib inline
pd.__version__

'1.1.5'

In [8]:
# para pandas = 2 decimales y seperación con , los miles
pd.options.display.float_format = '{:,.2f}'.format

In [9]:
# para numpy la presición en 2 decimales
np.set_printoptions(precision=2)

In [18]:
# creamos una matriz de 2 por 5 con valores entre 0 y 100 aleatorios
# rand = [0, 1]
# randn = [-1, 1]
x1 = np.random.rand(2,5)*10
x1

array([[2.76, 5.74, 0.04, 9.87, 6.44],
       [2.81, 8.8 , 8.11, 0.83, 7.45]])

In [19]:
x2 = np.random.rand(2,5)*-1
x2

array([[-0.9 , -0.56, -0.13, -0.13, -1.  ],
       [-0.27, -0.57, -0.93, -0.05, -0.96]])

In [20]:
# concatenamos matrices
np.concatenate([x1,x2])

array([[ 2.76,  5.74,  0.04,  9.87,  6.44],
       [ 2.81,  8.8 ,  8.11,  0.83,  7.45],
       [-0.9 , -0.56, -0.13, -0.13, -1.  ],
       [-0.27, -0.57, -0.93, -0.05, -0.96]])

In [21]:
np.concatenate([x1,x2]).shape

(4, 5)

In [22]:
np.concatenate([x1,x2], axis = 1)

array([[ 2.76,  5.74,  0.04,  9.87,  6.44, -0.9 , -0.56, -0.13, -0.13,
        -1.  ],
       [ 2.81,  8.8 ,  8.11,  0.83,  7.45, -0.27, -0.57, -0.93, -0.05,
        -0.96]])

In [23]:
np.concatenate([x1,x2], axis = 1).shape

(2, 10)

In [30]:
s1 = pd.Series(x1[0], index = ['a','b','c','d','e'])
s1

a   2.76
b   5.74
c   0.04
d   9.87
e   6.44
dtype: float64

In [31]:
s2 = pd.Series(x2[0], index = ['c','d','e','f','g'])
s2

c   -0.90
d   -0.56
e   -0.13
f   -0.13
g   -1.00
dtype: float64

In [37]:
pd.concat([s1, s2], ignore_index= True, axis = 1)

0     1
a 2.76   nan
b 5.74   nan
c 0.04 -0.90
d 9.87 -0.56
e 6.44 -0.13
f  nan -0.13
g  nan -1.00

In [39]:
s1.reset_index(drop = True, inplace = True)
s1

0   2.76
1   5.74
2   0.04
3   9.87
4   6.44
dtype: float64

In [40]:
s2.reset_index(drop = True, inplace = True)
s2

0   -0.90
1   -0.56
2   -0.13
3   -0.13
4   -1.00
dtype: float64

In [41]:
pd.concat([s1,s2], axis = 1, ignore_index = True)

0     1
0 2.76 -0.90
1 5.74 -0.56
2 0.04 -0.13
3 9.87 -0.13
4 6.44 -1.00

In [43]:
df1 = pd.DataFrame(np.random.rand(3,2)*10, columns = ['a', 'b'])
df1

a    b
0 2.99 7.41
1 5.52 6.75
2 8.15 4.40

In [45]:
df2 = pd.DataFrame(np.random.rand(3,2)*-1, columns = ['a', 'b'], index = [2,3,4])
df2

a     b
2 -0.75 -0.43
3 -0.81 -0.94
4 -0.41 -0.31

In [51]:
pd.concat([df1,df2], axis = 0, ignore_index=True)

a     b
0  2.99  7.41
1  5.52  6.75
2  8.15  4.40
3 -0.75 -0.43
4 -0.81 -0.94
5 -0.41 -0.31

In [53]:
pd.concat([df1,df2], axis = 1, ignore_index=True)

0    1     2     3
0 2.99 7.41   nan   nan
1 5.52 6.75   nan   nan
2 8.15 4.40 -0.75 -0.43
3  nan  nan -0.81 -0.94
4  nan  nan -0.41 -0.31

In [54]:
pd.concat([df1,df2], axis = 1, ignore_index=True, join='inner')

0    1     2     3
2 8.15 4.40 -0.75 -0.43

In [55]:
pd.concat([df1.reset_index(drop=True)
           ,df2.reset_index(drop=True)
           ], axis = 1, ignore_index=True, join='inner')

0    1     2     3
0 2.99 7.41 -0.75 -0.43
1 5.52 6.75 -0.81 -0.94
2 8.15 4.40 -0.41 -0.31

In [56]:
df1.T.append(df2.T).T

a    b     a     b
0 2.99 7.41   nan   nan
1 5.52 6.75   nan   nan
2 8.15 4.40 -0.75 -0.43
3  nan  nan -0.81 -0.94
4  nan  nan -0.41 -0.31

In [57]:
df1.append(df2)

a     b
0  2.99  7.41
1  5.52  6.75
2  8.15  4.40
2 -0.75 -0.43
3 -0.81 -0.94
4 -0.41 -0.31